---
GEMINI_API_KEY: <gemini-api-key>

development:
  DB_FILENAME: db/local/<db-name>.db
  REDISCLOUD_URL: <rediscloud-url>
  API_HOST: http://localhost:9090
  LOCAL_CACHE: _cache/rack
  AWS_ACCESS_KEY_ID: <aws-access-key-id>
  AWS_SECRET_ACCESS_KEY: <aws-secret-access-key>
  AWS_REGION: <sqs-queue-region>
  QUEUE: <sqs-queue-name>
  QUEUE_URL: <sqs-queue-url>

app_test:
  DB_FILENAME: db/local/<db-name>.db
  API_HOST: http://localhost:9090
  AWS_ACCESS_KEY_ID: <aws-access-key-id>
  AWS_SECRET_ACCESS_KEY: <aws-secret-access-key>
  AWS_REGION: <sqs-queue-region>
  QUEUE: <sqs-queue-name>
  QUEUE_URL: <sqs-queue-url>

test:
  DB_FILENAME: db/local/<db-name>.db
  API_HOST: http://localhost:9090
  AWS_ACCESS_KEY_ID: <aws-access-key-id>
  AWS_SECRET_ACCESS_KEY: <aws-secret-access-key>
  AWS_REGION: <sqs-queue-region>
  QUEUE: <sqs-queue-name>
  QUEUE_URL: <sqs-queue-url>

production:
  REDISCLOUD_URL: <rediscloud-url>
  API_HOST:  https://<heroku-app-name>
  AWS_ACCESS_KEY_ID: <aws-access-key-id>
  AWS_SECRET_ACCESS_KEY: <aws-secret-access-key>
  AWS_REGION: <sqs-queue-region>
  QUEUE: <sqs-queue-name>
  QUEUE_URL: <sqs-queue-url>